# Generated by Django 3.1.7 on 2021-03-02 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210302_0726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='password',
        ),
        migrations.AlterField(
            model_name='author',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
