# Generated by Django 3.1.7 on 2021-03-03 04:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='published',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='like',
            name='published',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
