# Generated by Django 3.1.7 on 2021-03-05 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_friendrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='status',
            field=models.CharField(choices=[('R', 'Requested'), ('A', 'Accepted')], default='Requested', max_length=1),
        ),
    ]
