# Generated by Django 3.1.6 on 2021-03-05 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
