# Generated by Django 3.1.6 on 2021-03-05 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
    ]
